# Generated by Django 6.0.6 on 2026-06-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('query_type', models.CharField(max_length=20)),
                ('result_city', models.CharField(blank=True, default='', max_length=100)),
                ('result_country', models.CharField(blank=True, default='', max_length=10)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['query_type'], name='weather_sea_query_t_33b105_idx'), models.Index(fields=['timestamp'], name='weather_sea_timesta_6283c3_idx')],
            },
        ),
    ]
